# Generated by Django 5.2.4 on 2025-07-20 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_addcart_addproduct_delete_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addcart',
            name='image',
        ),
        migrations.RemoveField(
            model_name='addcart',
            name='producti_category',
        ),
        migrations.RemoveField(
            model_name='addcart',
            name='producti_id',
        ),
        migrations.RemoveField(
            model_name='addcart',
            name='producti_name',
        ),
        migrations.RemoveField(
            model_name='addcart',
            name='producti_price',
        ),
        migrations.RemoveField(
            model_name='addcart',
            name='producti_qty',
        ),
        migrations.RemoveField(
            model_name='addcart',
            name='totalprice',
        ),
        migrations.AddField(
            model_name='addcart',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.addproduct'),
        ),
        migrations.AddField(
            model_name='addcart',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='category',
            field=models.CharField(default='uncategorized', max_length=100),
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='product_description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='product_offerprice',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='product_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
