# Generated by Django 5.2.3 on 2025-07-29 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_billiingdetails_delete_billingdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='cnt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('message', models.CharField(max_length=50)),
            ],
        ),
    ]
