# Generated by Django 5.2.4 on 2025-07-20 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addcart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producti_id', models.CharField(max_length=100)),
                ('producti_name', models.CharField(max_length=100)),
                ('producti_price', models.CharField(max_length=100)),
                ('producti_category', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to=100)),
                ('producti_qty', models.CharField(max_length=100)),
                ('totalprice', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Addproduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_description', models.CharField(max_length=100)),
                ('product_price', models.CharField(max_length=100)),
                ('product_offerprice', models.CharField(max_length=100)),
                ('category', models.CharField(default='uncatagorize', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image')),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
