# Generated by Django 4.2.7 on 2025-07-22 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_addcart_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addproduct',
            old_name='product_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='addproduct',
            old_name='product_offerprice',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='addproduct',
            name='category',
        ),
        migrations.RemoveField(
            model_name='addproduct',
            name='product_description',
        ),
        migrations.RemoveField(
            model_name='addproduct',
            name='product_price',
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
