# Generated by Django 4.2.7 on 2025-09-18 10:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_cnt'),
    ]

    operations = [
        migrations.AddField(
            model_name='billiingdetails',
            name='card_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='billiingdetails',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='billiingdetails',
            name='cvv',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='billiingdetails',
            name='expiry_date',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='billiingdetails',
            name='payment_method',
            field=models.CharField(choices=[('online', 'Online Payment'), ('cod', 'Cash on Delivery')], default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='billiingdetails',
            name='upi_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='billiingdetails',
            name='Address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='billiingdetails',
            name='emailaddress',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='billiingdetails',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='billiingdetails',
            name='zip',
            field=models.CharField(max_length=20),
        ),
    ]
