# Generated by Django 4.2.7 on 2025-09-19 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_billiingdetails_card_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billiingdetails',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='billiingdetails',
            old_name='cart_id',
            new_name='cart',
        ),
        migrations.AddField(
            model_name='billiingdetails',
            name='line_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='billiingdetails',
            name='payment_method',
            field=models.CharField(choices=[('online', 'Online Payment'), ('cod', 'Cash on Delivery')], default='cod', max_length=10),
        ),
    ]
